server:
  port: 8088

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: D8629753-DF40-4156-B452-51A204CD49AC
    url: jdbc:p6spy:mysql://cdb-b9e1arcc.cd.tencentcdb.com:10004/hera_test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    hikari:
      maxLifetime: 500000

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  typeEnumsPackage: net.peihuan.tieba_tool.constant
